name: cms-comp3
recipe: lamp
config:
  webroot: web
  php: '8.2'
  xdebug: true
  config:
    php: lando/php.ini
services:
  appserver:
    xdebug: true
    config:
      php: lando/php.ini
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
proxy:
  appserver:
    - cms-comp3.lndo.site
    - cms-comp4.lndo.site
tooling:
  craft:
    service: appserver
    cmd: php craft
    dir: /app
  xdebug-on:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo

  xdebug-off:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo