field: 4c2973da-f0f3-4062-a4c2-545b4aa40608 # sections
fieldLayouts:
  1263843d-9d57-4fc2-b017-2c9677ed7d5c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8e4b7985-a087-435c-91c7-544630d5a65b # Reusable
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76781871-4dd8-401a-9902-8a0ed3df7c03
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3c1d4b1e-0cad-46be-b104-277cd71aa6a5
        userCondition: null
fields:
  8e4b7985-a087-435c-91c7-544630d5a65b: # Reusable
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: reusable
    instructions: null
    name: Reusable
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: true
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      selectionLabel: null
      showSiteMenu: false
      sources:
        - 'section:da258fd9-e08e-4ba9-a5cb-8673f7825e51' # Reusable sections
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: reusable
name: reusable
sortOrder: 2
