field: 15bca145-bbc9-414a-bedd-d1216c071f87 # Top
fieldLayouts:
  f3c07120-34f0-4a6f-adf2-0aa7bc3ab949:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 368eac59-6924-4e60-80e5-b78c9f3894a5 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68be6c3f-98d2-4605-8aa5-3f041c7ecff3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b5d8503-f709-4bfa-8eb7-ef788eaaceed # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8d784c9-ac3d-44c4-853e-dcb7411d2285
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59669703-50aa-48db-9eee-2f5de818ba9c
        userCondition: null
fields:
  0b5d8503-f709-4bfa-8eb7-ef788eaaceed: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:becdda3e-ef63-4634-9c41-6fe4612d2428' # public
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:becdda3e-ef63-4634-9c41-6fe4612d2428' # public
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  368eac59-6924-4e60-80e5-b78c9f3894a5: # Text
    columnSuffix: rdwyksfy
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 83f03672-8bf4-4167-9375-03a423bc5cdf # Simple
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\ckeditor\Field
handle: textMedia
name: 'text & media'
sortOrder: 1
