field: 4c2973da-f0f3-4062-a4c2-545b4aa40608 # sections
fieldLayouts:
  ff74d766-f12b-423a-974c-3c5587d7af36:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dcd69f7c-1533-46a0-ae81-8d1e390a1cfb # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6359cb38-cfba-49c3-a1b0-1c7070c56a06
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7319b25b-5d3b-460a-bd07-faf2a2b640f5 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e62ea98a-07cd-45ce-80b7-01385242a66b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 972f3d9c-7c30-4792-971f-6bc3625e85a1
        userCondition: null
fields:
  7319b25b-5d3b-460a-bd07-faf2a2b640f5: # Text
    columnSuffix: dlumtdde
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 83f03672-8bf4-4167-9375-03a423bc5cdf # Simple
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\ckeditor\Field
  dcd69f7c-1533-46a0-ae81-8d1e390a1cfb: # Title
    columnSuffix: ovwiyoeg
    contentColumnType: text
    fieldGroup: null
    handle: text_title
    instructions: null
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: text
name: Text
sortOrder: 1
