fieldLayouts:
  a4f93840-8ad4-4243-8294-e2ea164b38a9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f801f47a-fcdb-4afb-a465-755e6b1e683f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4c2973da-f0f3-4062-a4c2-545b4aa40608 # sections
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31306464-29e0-438d-8ed1-054697aca6b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ac1ec4b-f31f-4865-afc9-23427f337b7a
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 5105d55e-d0a9-41b5-884d-92ef10711462 # On one language
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
