color: null
fieldLayouts:
  ff74d766-f12b-423a-974c-3c5587d7af36:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dcd69f7c-1533-46a0-ae81-8d1e390a1cfb
            handle: text_title
            includeInCards: true
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6359cb38-cfba-49c3-a1b0-1c7070c56a06
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7319b25b-5d3b-460a-bd07-faf2a2b640f5
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e62ea98a-07cd-45ce-80b7-01385242a66b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 972f3d9c-7c30-4792-971f-6bc3625e85a1
        userCondition: null
handle: text2
hasTitleField: false
icon: null
name: 'Text 2'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
