color: null
fieldLayouts:
  f3c07120-34f0-4a6f-adf2-0aa7bc3ab949:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 368eac59-6924-4e60-80e5-b78c9f3894a5 # Top - text & media - Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68be6c3f-98d2-4605-8aa5-3f041c7ecff3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b5d8503-f709-4bfa-8eb7-ef788eaaceed # Top - text & media - Image
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8d784c9-ac3d-44c4-853e-dcb7411d2285
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59669703-50aa-48db-9eee-2f5de818ba9c
        userCondition: null
handle: textMedia2
hasTitleField: false
icon: null
name: 'text & media'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
