color: null
fieldLayouts:
  4595fc47-7cb7-44fc-bf3a-d9b373cdf0de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3704af8-eb4f-4de1-8a2e-2fa7b6fd2955 # Bottom - Text & media - Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19685c7b-5c93-44b1-9d65-5375ef09b12d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fa31f7c-33a9-4c0c-aa25-bf9d18f320cb # Bottom - Text & media - Image
            handle: null
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 275d3cec-fe2a-4f99-abb3-ec169bf62eab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5730ab26-7679-4b05-a347-59d3c5935a27
        userCondition: null
handle: textMedia
hasTitleField: false
icon: null
name: 'Text & media'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
