defaultPlacement: end
fieldLayouts:
  ab3f0e3d-a46b-424b-91e9-a96dd2b5ebca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 55d923ac-ea08-4dec-89d2-89d1994585b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 104edcda-7409-4a06-bb8c-5e543b224f52
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 8adb979b-4cd1-4af9-920c-d7f8d3710244
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 5f2c316d-c251-43de-8953-295376266fb6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 813dc1af-09da-49e8-8602-1f474a3fc7d4
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: ad016469-49f2-4cec-b4b8-4131f6f585b1
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 03149873-d26d-4c3a-a773-854a6eefd176
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 24183ee5-9fd9-4ef3-8b6d-63a25dfda604
        userCondition: null
handle: main
instructions: ''
maxNodes: null
name: 'main 1'
permissions:
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions:
      - 'section:55269202-1fff-49bd-97c7-38ce025f46ee' # On one site
      - 'section:5105d55e-d0a9-41b5-884d-92ef10711462' # On one language
      - 'section:116ce282-ae1c-4bec-a84d-5aacadad3ea4' # Fixed template
      - singles
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagationMethod: language
siteSettings:
  3bf95ece-687f-47dc-af48-e3b21d67cd70: # nl 1
    enabled: true
  7c87c1b1-8258-4dc2-be88-9a023ba59de7: # en1
    enabled: true
  9df8ca98-7fae-4523-8a3c-2b237f90d1da: # fr 2
    enabled: false
  222bc59b-a78b-418d-bf26-7d2ca2c3c053: # fr 1
    enabled: true
  b224667f-40f1-495b-a4e5-d7f03067a9a4: # en 2
    enabled: false
  e912387a-a004-4771-a91e-3bd0f67929da: # nl 2
    enabled: false
sortOrder: 1
structure:
  maxLevels: null
  uid: 5b402ac7-1270-4360-987f-fdcec0a16eaf
