columnSuffix: null
contentColumnType: string
handle: bottom
instructions: null
name: Bottom
searchable: false
settings:
  entryTypes:
    - 7aa10b97-ad2b-44d4-95fa-f0ccc16bfdfa
  maxEntries: 1
  minEntries: 1
  propagationKeyFormat: null
  propagationMethod: none
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
