columnSuffix: null
contentColumnType: string
fieldGroup: bcca1c51-0096-430f-b114-7fa1a68cd5ea # Common
handle: bottom
instructions: null
name: Bottom
searchable: false
settings:
  contentTable: '{{%matrixcontent_bottom}}'
  maxBlocks: 1
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
