columnSuffix: null
contentColumnType: string
handle: reusables
instructions: null
name: reusables
searchable: false
settings:
  entryTypes:
    - c463f92a-7914-4564-a9b0-b0e80b11df1b
  maxEntries: 1
  minEntries: 1
  propagationKeyFormat: null
  propagationMethod: none
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
