columnSuffix: null
contentColumnType: string
handle: top
instructions: null
name: Top
searchable: false
settings:
  entryTypes:
    - 798b8e18-0efe-4e7b-9326-ae32cf64d3bc
  maxEntries: 1
  minEntries: 1
  propagationKeyFormat: null
  propagationMethod: none
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
