defaultPlacement: end
enableVersioning: true
handle: fixedTemplate
name: 'Fixed template'
propagationMethod: none
siteSettings:
  3bf95ece-687f-47dc-af48-e3b21d67cd70: # nl 1
    enabledByDefault: true
    hasUrls: true
    template: fixed
    uriFormat: '{slug}'
  7c87c1b1-8258-4dc2-be88-9a023ba59de7: # en 1
    enabledByDefault: true
    hasUrls: true
    template: fixed
    uriFormat: '{slug}'
  9df8ca98-7fae-4523-8a3c-2b237f90d1da: # fr 2
    enabledByDefault: true
    hasUrls: true
    template: fixed
    uriFormat: '{slug}'
  222bc59b-a78b-418d-bf26-7d2ca2c3c053: # fr 1
    enabledByDefault: true
    hasUrls: true
    template: fixed
    uriFormat: '{slug}'
  b224667f-40f1-495b-a4e5-d7f03067a9a4: # en 2
    enabledByDefault: true
    hasUrls: true
    template: fixed
    uriFormat: '{slug}'
  e912387a-a004-4771-a91e-3bd0f67929da: # nl 2
    enabledByDefault: true
    hasUrls: true
    template: fixed
    uriFormat: '{slug}'
type: channel
