defaultPlacement: end
enableVersioning: true
entryTypes:
  - a6d71d18-7a28-457e-8873-f3a613eea5ee # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  3bf95ece-687f-47dc-af48-e3b21d67cd70: # nl 1
    enabledByDefault: true
    hasUrls: true
    template: sections
    uriFormat: __home__
  7c87c1b1-8258-4dc2-be88-9a023ba59de7: # en1
    enabledByDefault: true
    hasUrls: true
    template: sections
    uriFormat: __home__
  9df8ca98-7fae-4523-8a3c-2b237f90d1da: # fr 2
    enabledByDefault: true
    hasUrls: true
    template: sections
    uriFormat: __home__
  222bc59b-a78b-418d-bf26-7d2ca2c3c053: # fr 1
    enabledByDefault: true
    hasUrls: true
    template: sections
    uriFormat: __home__
  b224667f-40f1-495b-a4e5-d7f03067a9a4: # en 2
    enabledByDefault: true
    hasUrls: true
    template: sections
    uriFormat: __home__
  e912387a-a004-4771-a91e-3bd0f67929da: # nl 2
    enabledByDefault: true
    hasUrls: true
    template: sections
    uriFormat: __home__
type: single
