defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7d3a4a01-3a0f-415b-84a4-19a062ee83be # Default
handle: onOneSite
maxAuthors: 1
name: 'On one site'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: none
siteSettings:
  3bf95ece-687f-47dc-af48-e3b21d67cd70: # nl 1
    enabledByDefault: true
    hasUrls: true
    template: sections
    uriFormat: '{slug}'
  7c87c1b1-8258-4dc2-be88-9a023ba59de7: # en1
    enabledByDefault: true
    hasUrls: true
    template: sections
    uriFormat: '{slug}'
  222bc59b-a78b-418d-bf26-7d2ca2c3c053: # fr 1
    enabledByDefault: true
    hasUrls: true
    template: sections
    uriFormat: '{slug}'
type: channel
