defaultPlacement: end
enableVersioning: true
entryTypes:
  - 606a7cae-404c-4c84-9377-79d2158ea7b7 # reusable
handle: reusableSections
name: 'Reusable sections'
propagationMethod: siteGroup
siteSettings:
  3bf95ece-687f-47dc-af48-e3b21d67cd70: # nl 1
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  7c87c1b1-8258-4dc2-be88-9a023ba59de7: # en1
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  9df8ca98-7fae-4523-8a3c-2b237f90d1da: # fr 2
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  222bc59b-a78b-418d-bf26-7d2ca2c3c053: # fr 1
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  b224667f-40f1-495b-a4e5-d7f03067a9a4: # en 2
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  e912387a-a004-4771-a91e-3bd0f67929da: # nl 2
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
